[build-system]
requires = ["python-doctr>=0.2.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "doctr-api"
version = "0.6.0a0"
description = "Backend template for your OCR API with docTR"
authors = ["Mindee <contact@mindee.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = ">=0.11.1"
fastapi = ">=0.65.2,<1.0.0"
python-multipart = "==0.0.5"

[tool.poetry.dev-dependencies]
pytest = ">=5.3.2,<8.0.0"
pytest-asyncio = ">=0.14.0,<1.0.0"
httpx = ">=0.23.0"
requests = "^2.20.0"
