name: docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  docker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t doctr-py3.8.1-tf2.4-slim
      - name: Run docker container
        run: docker run doctr-py3.8.1-tf2.4-slim python -c 'import doctr'

  pytest-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run docker
        run: PORT=8002 docker-compose up -d --build
      - name: Install dependencies in docker
        run: |
          PORT=8002 docker-compose exec -T web python -m pip install --upgrade pip
          PORT=8002 docker-compose exec -T web pip install -r requirements-dev.txt
      - name: Run docker test
        run: PORT=8002 docker-compose exec -T web pytest .
