name: references

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-classification:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
        framework: [tensorflow, pytorch]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - if: matrix.framework == 'tensorflow'
        name: Cache python modules (TF)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('references/requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('references/requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-
      - if: matrix.framework == 'pytorch'
        name: Cache python modules (PT)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-${{ hashFiles('references/requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-${{ hashFiles('references/requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-

      - if: matrix.framework == 'tensorflow'
        name: Install dependencies (TF)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
          pip install -r references/requirements.txt
          sudo apt-get update && sudo apt-get install fonts-freefont-ttf -y
      - if: matrix.framework == 'pytorch'
        name: Install dependencies (PT)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[torch] --upgrade
          pip install -r references/requirements.txt
          pip install contiguous-params
          sudo apt-get update && sudo apt-get install fonts-freefont-ttf -y
      - if: matrix.framework == 'tensorflow'
        name: Train for a short epoch (TF)
        run: python references/classification/train_tensorflow.py mobilenet_v3_small -b 32 --val-samples 1 --train-samples 1 --epochs 1
      - if: matrix.framework == 'pytorch'
        name: Train for a short epoch (PT)
        run: python references/classification/train_pytorch.py mobilenet_v3_small -b 32 --val-samples 1 --train-samples 1 --epochs 1

  test-recognition:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
        framework: [tensorflow, pytorch]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - if: matrix.framework == 'tensorflow'
        name: Cache python modules (TF)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('references/requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('references/requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-
      - if: matrix.framework == 'pytorch'
        name: Cache python modules (PT)
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-${{ hashFiles('references/requirements.txt') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-${{ hashFiles('references/requirements.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements-pt.txt') }}-
            ${{ runner.os }}-pkg-deps-${{ matrix.python }}-
            ${{ runner.os }}-pkg-deps-
            ${{ runner.os }}-

      - if: matrix.framework == 'tensorflow'
        name: Install dependencies (TF)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf] --upgrade
          pip install -r references/requirements.txt
      - if: matrix.framework == 'pytorch'
        name: Install dependencies (PT)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[torch] --upgrade
          pip install -r references/requirements.txt
          pip install contiguous-params
      - name: Download and extract toy set
        run: |
          wget https://github.com/mindee/doctr/releases/download/v0.3.1/toy_recogition_set-036a4d80.zip
          sudo apt-get update && sudo apt-get install unzip -y
          unzip toy_recogition_set-036a4d80.zip -d reco_set
      - if: matrix.framework == 'tensorflow'
        name: Train for a short epoch (TF)
        run: python references/recognition/train_tensorflow.py ./reco_set ./reco_set crnn_vgg16_bn -b 4 --epochs 1
      - if: matrix.framework == 'pytorch'
        name: Train for a short epoch (PT)
        run: python references/recognition/train_pytorch.py ./reco_set ./reco_set crnn_mobilenet_v3_small -b 4 --epochs 1
