name: testpackageinstall

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  pypi-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install package
        run: |
          python -m pip3 install --upgrade pip
          pip3 install python-doctr[torch]
          python3 -c "import doctr; print(doctr.__version__)"

  conda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: pypdfium2-team,bblanchon,techMindee,defaults,conda-forge,pytorch
          channel-priority: strict
      - name: Install package
        shell: bash -el {0}
        run: |
          conda config --show channels
          conda install python-doctr
          conda install pytorch torchvision torchaudio
          python -c "import doctr; print(doctr.__version__)"
