name: testpackageinstall

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  pypi-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install python-doctr[torch]
          python -c "from importlib.metadata import version; print(version('python-doctr'))"

  conda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: pypdfium2-team,bblanchon,techMindee,defaults,conda-forge
          channel-priority: strict
      - name: Install package
        shell: bash -el {0}
        run: |
          pip3 install torch torchvision torchaudio
          conda config --set channel_priority strict
          conda install -c techMindee -c pypdfium2-team -c bblanchon -c defaults -c conda-forge python-doctr
          conda list python-doctr
          python -c "from importlib.metadata import version; print(version('python-doctr'))"
